server:
    port: 8888
spring:     #Spring Cloud Server Repository
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/esau97/configServer
                    default-label: main
                    search-paths:                    - 'service'